making app run on android
Team1690/Scouting-Frontend pull request #155
Opened 2022-01-25 19:50 UTC by itamarsch

I tried running the pc view on a tablet if mine and there were  few small bugs mainly because of the fact that javasript has only `number` and java has number types but currently it actually looks pretty good and usable and maybe a future option

2022-01-26 00:44 UTC, giladwo requested changes

2022-01-26 00:44 UTC, giladwo commented on lib/views/pc/widgets/scatter.dart
> +                final List<int> matchBallPoints = matches
If `matchBallPoints` is only traversed once there's no need for a fully materialized collection, just leave it an `Interable`

2022-01-26 07:44 UTC, itamarsch commented on lib/views/pc/compare_screen.dart
> +  List<int> points;
I have no idea why I made all of them double because this value is actually an int but when running on web this doesn't really matter because there only is number

2022-01-26 09:10 UTC, itamarsch commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
maybe using [`num`](https://api.dart.dev/stable/2.15.1/dart-core/num-class.html)

2022-01-26 09:46 UTC, itamarsch commented on lib/views/pc/compare_screen.dart
>                              .toList(),
the `toList` are needed because `map<E>` return an `Iterable<E>` and this argument recieves a `List<List<double>>` so we need to turn the Iterable to a list for the types to match

2022-01-26 11:14 UTC, giladwo requested changes

2022-01-26 11:14 UTC, giladwo commented on lib/views/pc/compare_screen.dart
> +                climbLineChart(climb)
Nicely done

2022-01-26 11:14 UTC, giladwo commented on lib/views/pc/widgets/scatter.dart
>                      .toList();
The important bit is to remove this unnecessary `toList` because we don't ever need all the elements at the same time.

2022-01-26 11:19 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
Using `num` would let us have different sub-types of `num` in the same collection, which is dangerous.
The trick is to use parametricity - just like we've changed `Selector` to `Selector<T>` because we don't really care what the underlying representation of its options is.
So this widget should be parametrized by any `<T>` (or if we need numerical operations by any `<T extends num>`.

2022-01-26 11:51 UTC, giladwo commented on lib/views/pc/compare_screen.dart
>                              .toList(),
Indeed, but that applies only to the inner iterables.

2022-01-26 11:56 UTC, giladwo commented
I encourage you to watch [Why functional programming matters / John Hughes @ Functional Conf 2016](https://www.youtube.com/watch?v=XrNdvWqxBvA).
It provides an overview of quite a few important ideas, including function as a data structure (overcharged https://github.com/Team1690/Scouting-Frontend/pull/155#discussion_r792537898) and laziness (exactly what https://github.com/Team1690/Scouting-Frontend/pull/155#discussion_r792534575 is all about).

@NoamPrag I think you'd find this interesting too.

2022-01-26 11:56 UTC, itamarsch commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
So DashboardLinechart should receive a `List<E extends num>` and call `. to Double` internally?

2022-01-26 13:31 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
No, it should be a `DashboardLineChart<E extends num>` and it should have a `List<E>` member.
What needs `.toDouble`?

2022-01-26 14:58 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
It should be `LineChartData<E extends num>`

2022-01-26 16:12 UTC, itamarsch commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
I now added this in both CompareChartData and LineChartData

2022-01-26 16:29 UTC, giladwo requested changes

2022-01-26 16:29 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +          final LineChartData<int> climbData = LineChartData<int>(
Our goal is not to have to change a million places when the underlying representation changes.
There still are multiple changes - this means this scope should be parametrized as well - it should be `Team<T extends num>`.
This would turn all these `List<int>`s into `List<T>`s.
Keep pushing the parametricity outwards until the we truly only need to decide once (change a single place) what the underlying type is.

2022-01-26 16:31 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +  List<List<int>> points;
And still - many places are changed. This indicates the current scope should be parametrized as well.
Remember - the goal is to change this in a single place, not in many interdependent places.

2022-01-26 18:48 UTC, itamarsch commented
@giladwo I think I implemented it correctly does it look good to you?

2022-01-26 18:55 UTC, giladwo reviewed
One can always push type parameters outwards, i.e. make compare screen parameterized, but if you're okay with the current situation it should be okay. You're the one who has to change a lot of places.

2022-01-26 18:58 UTC, itamarsch commented
I think that is a good idea that way I only write the type in one place keeps some errors away

2022-01-26 19:49 UTC, itamarsch commented
@giladwo can you approve changes so I can merge?

2022-01-26 20:51 UTC, Ido-Sobol approved these changes

2022-01-26 20:53 UTC, itamarsch commented
> @giladwo can you approve changes so I can merge?

ping @giladwo

2022-01-26 20:59 UTC, itamarsch commented
> 

but you requeted changes so it doesn't let me merge

2022-01-26 21:00 UTC, giladwo approved these changes
Fix these before you merge

2022-01-26 21:01 UTC, itamarsch commented on lib/views/pc/widgets/team_info_data.dart
> +    return climbPoints[0].toDouble();
don't know but we'll just pray that we don''t have anything simular somewhere else

2022-01-26 21:05 UTC, itamarsch commented on lib/views/pc/widgets/team_info_data.dart
> +                  .map((final dynamic e) => e["auto_upper"] as int)
but if E is double this won't workjust like it didn't back in the start

2022-01-26 21:12 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +                  .map((final dynamic e) => e["auto_upper"] as int)
Then all this is kinda pointless

2022-01-26 21:14 UTC, merged

2022-01-27 10:43 UTC, giladwo commented on lib/views/pc/widgets/team_info_data.dart
> +    return climbPoints[0].toDouble();
https://twitter.com/joepolitz/status/1486179719967952902?t=9GIaPV_6BEzvaqqISztvxA