Dashboard faults
Team1690/Scouting-Frontend pull request #195
Opened 2022-02-17 13:17 UTC by itamarsch

2022-02-17 14:34 UTC, giladwo commented on lib/views/pc/picklist/pick_list_widget.dart
> +    required final String faultMessage,
See https://github.com/Team1690/Scouting-Frontend/pull/194#discussion_r807963391 (and the other comments).

2022-02-19 16:51 UTC, Ido-Sobol approved these changes

2022-02-20 10:46 UTC, itamarsch commented on lib/views/pc/picklist/pick_list_widget.dart
> +    required final String faultMessage,
fixed here

2022-02-20 18:50 UTC, giladwo requested changes

2022-02-20 18:50 UTC, giladwo commented on lib/views/pc/picklist/fetch_picklist.dart
> +              faultMessage: teamIdToFaultMessage[e["id"] as int] ?? "",
Still here

2022-02-20 18:50 UTC, giladwo commented on lib/views/pc/picklist/pick_list_widget.dart
> +          faultMessage,
Still here

2022-02-20 18:50 UTC, giladwo commented on lib/views/pc/picklist/pick_list_widget.dart
> +    this.faultMessage,
Still here

2022-02-20 18:50 UTC, giladwo commented on lib/views/pc/picklist/pick_list_widget.dart
> +  final String faultMessage;
Still here

2022-02-20 18:50 UTC, giladwo commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
WTH is `team_info_classes.dart`?
There's no point in creating a module just for "classes", just like there's no point in creating a "functions" or a "constants" module (**ahem**).
They don't exist for their own sake, they're means to an end.
They're merely implementation details of the module that needs them, and therefore they should be embedded there privately.

2022-02-20 18:50 UTC, giladwo commented on lib/views/pc/picklist/pick_list_widget.dart
> +    required final String faultMessage,
This should be changed everywhere.

2022-02-20 19:30 UTC, itamarsch commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
I understand what you are saying here but how do I make the use of a class private?

2022-02-20 20:01 UTC, itamarsch commented on lib/views/pc/picklist/fetch_picklist.dart
> +              faultMessage: teamIdToFaultMessage[e["id"] as int] ?? "",
fixed this and all the others

2022-02-21 13:19 UTC, giladwo commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
To make a global symbol private in Dart, you just prefix its name with `_`.
It's a nice touch, but the most important part is having the symbol in the correct scope (module) to begin with.

2022-02-21 13:33 UTC, itamarsch commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
Actually now that I think.of it I use these classes in the coach screen because I have a screen which is basically the same data as team info but on the phone

2022-02-21 16:42 UTC, giladwo commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
So why not keep it dry and extract the common widget out?
If the widgets are different but deal with the same data, I'd still create a module that wraps them and provides both of them.

2022-02-21 16:56 UTC, itamarsch commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
Isn't a module that wraps both of them just team_info_classes?

2022-02-21 16:59 UTC, itamarsch commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
The widgets deal with the same data but look very differently

2022-02-21 17:31 UTC, giladwo commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
The classes by themselves are not the important part - the widgets are.
A good `team_info.dart` module would provide all the widgets the other parts of the app need, i.e. a `mobile` view, a `dashboard` view, etc.

2022-02-21 17:54 UTC, itamarsch commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
I think this isn't really related to this pr and we should merge this pr and open a different pr and an issue for changing the project structure

2022-02-21 19:46 UTC, itamarsch commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
@giladwo do you approve?

2022-02-21 21:35 UTC, giladwo approved these changes

2022-02-21 21:38 UTC, giladwo commented on lib/views/pc/team_info/models/team_info_classes.dart
>    final String notes;
This is what #116 is all about.
Indeed, this shouldn't block this PR.
However, some changes are better done quietly without much ceremony, like fixing such design errors (which should've been captured in the PR that introduced them).

2022-02-22 07:11 UTC, merged