Removing hasFault
Team1690/Scouting-Frontend pull request #196
Opened 2022-02-20 10:47 UTC by itamarsch

2022-02-20 17:46 UTC, itamarsch commented
@giladwo here are the things you wanted to change in #194

2022-02-20 18:55 UTC, giladwo requested changes

2022-02-20 18:55 UTC, giladwo commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
```dart
vars.faultMessage.onNull("")
```

Also, are you sure?
This changes `null` to `""`, so `vars.faultMessage` is never `null` after `setState`, which means there's always fault.
Doesn't seem right.

2022-02-20 19:34 UTC, itamarsch commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
But if its not null then it return to null in the else statment

2022-02-20 19:40 UTC, itamarsch commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
This works for me great locally so I dont really know what you're talking about

2022-02-21 13:16 UTC, giladwo commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
My point is that `vars.faultMessage != null` (which is the case if `vars.faultMessage == ""`) should mean there's no error, and `""` shouldn't be allowed (doesn't contain any useful information and `null` represents `ok`)..

2022-02-21 13:34 UTC, itamarsch commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
I can make the default value No data but would that really be better?

2022-02-21 16:43 UTC, giladwo commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
Yes, `""` means nothing.

2022-02-21 16:58 UTC, itamarsch commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
FIxed

2022-02-21 17:35 UTC, giladwo commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
@itamarsch What seems weird to me is that `vars.faultMessage` is unconditionally set to indicate fault if there's no fault and vice versa.

2022-02-21 17:45 UTC, itamarsch commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
Whats the problem with that?

2022-02-21 18:27 UTC, merged

2022-02-21 21:27 UTC, giladwo commented on lib/views/mobile/screens/specific_view.dart
> +                                    vars.faultMessage == null ? "" : null;
It doesn't make sense.
If there's no error, it should be null.
Otherwise, it should hold an indicative message.
That's not what it seems to be doing.