add team button and edit team button
Team1690/Scouting-Frontend pull request #217
Opened 2022-03-01 22:18 UTC by itamarsch

2022-03-02 00:29 UTC, giladwo requested changes

2022-03-02 00:29 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +              ).then((final void _) {});
This doesn't even do anything.

2022-03-02 00:29 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +                          addFaultTeam(team!.id, newMessage!)
🧐

2022-03-02 00:29 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +                            setState(() {});
Just figure out subscriptions already.

2022-03-02 00:29 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +              showDialog<void>(
You ignore the right way to get a result from `showDialog` only to reimplement it with error-prone mutation.

2022-03-02 05:50 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +              showDialog<void>(
I tried to write it the correct way like I did in the edit button but here I had two pieces of state and I couldn't find a way to make this work

2022-03-02 07:36 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +                          addFaultTeam(team!.id, newMessage!)
Its wierd that the compiler doesn't infer this

2022-03-02 07:37 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +              showDialog<void>(
I can make `StatefulWidget` for the `AlertDialog`

2022-03-02 07:50 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +              showDialog<void>(
I think I fixed this

2022-03-02 18:46 UTC, giladwo requested changes
Please try using gql subscriptions once again.
It shouldn't be any harder then using normal queries, and would be much better style (being the right tool for the job).

2022-03-02 18:46 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +              final FaultTeam? faultTeam = await showDialog<FaultTeam>(
`showDialog` yields a `LightTeam` and a `String` on successful termination, so there's no need for the mutable `team` & `newMessage` variables.
Just do whatever you want after you get the result.

2022-03-02 18:46 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +                              .pop(FaultTeam(newMessage!, team!));
You're not programming in C here, and there are better options then spaghetti nullity checks and many meaningless `return`s.
For instance, this can be restructured much more elegantly as
```dart
await showDialog<FaultTeam>(...).mapNullable(Navigator.of(context).pop);
```

Do note how `mapNullable` hides the "do nothing on failure" behavior and lets us focus solely on the happy path :slightly_smiling_face: .

2022-03-02 18:49 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +                          addFaultTeam(team!.id, newMessage!)
The compiler is usually correct.
In this case, `team` and `newMessage` are mutable nullable variables, so indeed they cannot be safely inferred as non-nullable values.
This is a strong indication a more elegant solution is possible (considering Dart's expressiveness).

2022-03-02 21:21 UTC, itamarsch commented
But we have tried and it said this
![image](https://user-images.githubusercontent.com/71348842/156451634-c3dfcd5f-9f37-414b-9337-6d70339290f9.jpeg)

2022-03-02 21:22 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +              final FaultTeam? faultTeam = await showDialog<FaultTeam>(
But how do I save what the user selected?

2022-03-03 11:00 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +                              .pop(FaultTeam(newMessage!, team!));
Fixed?

2022-03-04 15:00 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +              final FaultTeam? faultTeam = await showDialog<FaultTeam>(
That's what `showDialog` should return

2022-03-04 17:58 UTC, itamarsch commented on lib/views/mobile/screens/fault_view.dart
> +              final FaultTeam? faultTeam = await showDialog<FaultTeam>(
And how do I return only if both values are selected and and they press submit

2022-03-04 18:04 UTC, itamarsch commented
https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/index.html
I couldn't really find something related here probably because I don't really understand alot here do you see something here they looks helpful? I tried looking elsewhere but couldn't find something related

2022-03-04 19:08 UTC, itamarsch commented
I tried searching more about this but couldn't get to a solution

2022-03-05 20:37 UTC, itamarsch commented
I still don't understand how I can manage the state better here or how I can improve this can we merge this because I want this feature to be used in upcoming district (on monday)

2022-03-05 23:46 UTC, giladwo requested changes

2022-03-05 23:46 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +                              .pop(FaultTeam(newMessage!, team!));
No, instead of `actions` use `showDialog`'s result.

2022-03-05 23:46 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +                  setState(() {});
Now that we've got subscriptions working, all these `setState`s are redundant - just use a `StreamBuilder` and let the subscription trigger re-render automagically.

2022-03-05 23:48 UTC, giladwo commented on lib/views/mobile/screens/fault_view.dart
> +              final FaultTeam? faultTeam = await showDialog<FaultTeam>(
Ah, I see your point...
Sorry, I'm not used to Flutter's way of doing things.

2022-03-05 23:50 UTC, giladwo approved these changes

2022-03-05 23:51 UTC, giladwo commented
I'm approving this because the last day before the district should be spent discussing this.

2022-03-05 23:51 UTC, merged