Team view
Team1690/Scouting-Frontend pull request #248
Opened 2022-03-16 14:58 UTC by itamarsch

2022-03-16 16:23 UTC, giladwo commented on lib/views/pc/team_view/team_view_screen.dart
> +class TeamViewTeam {
How about a plain module-private `Team`? This is already inside a `team_view/team_view_screen` module (which should be simply named `screen` to reduce redundancy - `team_view/screen` or `screen/team_view`.

2022-03-16 16:25 UTC, giladwo commented on lib/views/pc/team_view/team_view_screen.dart
> +query MySubscription {
![image](https://user-images.githubusercontent.com/25708271/158638633-e3cc283e-50d9-4757-bf0c-87c00bfe85bf.png)

2022-03-16 16:29 UTC, giladwo commented on lib/views/pc/team_view/team_view_screen.dart
> +                                      ),
Don't you see a pattern here?

```dart
Widget show(final int x) => DataCell(Text(x == -1 ? "No data" : x.toStringAsFixed(1)));
```
and then these reduce to ```...<int>[e.teleUpperAvg, e.autoUpperAvg, ...].map<Widget>(show)```.

2022-03-16 17:12 UTC, itamarsch commented on lib/views/pc/team_view/team_view_screen.dart
> +                                      ),
cool solution to the duplication

2022-03-16 17:20 UTC, giladwo commented on lib/views/pc/team_view/team_view_screen.dart
> +                                      ),
There's no clever trick here. You're only allowed to create functions, so that's what you ought to do when faced with duplication.

2022-03-17 09:47 UTC, itamarsch commented on lib/views/pc/team_view/team_view_screen.dart
> +                                  },
I think I fixed this

2022-03-17 09:48 UTC, itamarsch commented
I think I added the things you wanted me to add

2022-03-19 00:56 UTC, giladwo requested changes
![image](https://user-images.githubusercontent.com/25708271/159100422-db30bf9a-6bcb-4083-ad08-8b247c137017.png)
Boilerplate, boilerplate everywhere

2022-03-19 00:56 UTC, giladwo commented on lib/views/pc/team_view/screen.dart
> +                                  }
```dart
final bool ascending = sortedColumn == index && !ascending;
```

2022-03-19 00:56 UTC, giladwo commented on lib/views/pc/team_view/screen.dart
> +                                                .compareTo(b.teleUpperAvg),
This duplication is completely unnecessary.
All these columns share (1) reverse order and (2) extract a numeric value from a `_Team`.
Thus, these should be incorporated into the `column` helper:
```dart
T reverseIf<T extends num>(final Bool condition, final T x) => condition ? -x : x;
DataColumn column(final String title, final num Function(_Team) f) =>
    DataColumn(
        label: Text(title),
        numeric: true,
        onSort: (final int index, final _ _) {
            setState(() {
                // not sure where is this needed, but here's a more elegant expression
                final bool ascending = sortedColumn == index && !isAscending;
                sortedColumn = index;
                data.sort((final bool descending) =>
                    (final _Team a, final _Team b) => reverseIf(descending, f(a).compareTo(f(b)))
                );
            };
        },
    );
```
Then, all these columns reduce to the important bits, i.e. `column("Auto upper", (final Team_ team) => team.autoUpperAvg)`.

2022-03-19 09:59 UTC, itamarsch commented
I felt like my solution wasn't so elegant

2022-03-19 15:00 UTC, giladwo requested changes
This `reverseIf` is actually more of a `reverseUnless`.

2022-03-19 15:00 UTC, giladwo commented on lib/views/pc/team_view/screen.dart
> +                        num reverseIf<T extends num>(
```suggestion
                        T reverseUnless<T extends num>(
```

2022-03-19 15:00 UTC, giladwo commented on lib/views/pc/team_view/screen.dart
> +                                    (final _Team a, final _Team b) => reverseIf(
```suggestion
                                    (final _Team a, final _Team b) => reverseUnless(
```

2022-03-19 15:01 UTC, itamarsch commented on lib/views/pc/team_view/screen.dart
> +                        num reverseIf<T extends num>(
This doesn't work because the operator - doesn't return a T it returns a num

2022-03-19 15:02 UTC, giladwo commented on lib/views/pc/team_view/screen.dart
> +                        num reverseIf<T extends num>(
:facepalm:

2022-03-19 15:14 UTC, itamarsch commented
![image](https://user-images.githubusercontent.com/71348842/159126789-12cf32d7-f09f-4c5c-9962-3d5c623a6af6.png)

2022-03-19 15:52 UTC, giladwo commented
> ![image](https://user-images.githubusercontent.com/71348842/159126789-12cf32d7-f09f-4c5c-9962-3d5c623a6af6.png)

:facepalm: 
Just fix it, you know what to do...

2022-03-19 16:27 UTC, itamarsch commented
> > ![image](https://user-images.githubusercontent.com/71348842/159126789-12cf32d7-f09f-4c5c-9962-3d5c623a6af6.png)
> 
> 
> 
> :facepalm: 
> 
> Just fix it, you know what to do...

This is already fixed

2022-03-19 18:24 UTC, giladwo approved these changes

2022-03-19 18:24 UTC, merged