Second biggest pr you've ever seen!
Team1690/Scouting-Frontend pull request #315
Opened 2022-11-28 17:37 UTC by ItayNaumann

changed the score to match the text color and alliance order

2022-12-06 18:41 UTC, giladwo requested changes
The comments were left from bottom up, so I'd start reading them in the same order to make them clearer (i.e. without forward references).

I'm sorry I can't take more time to be as active as I probably should be here, but I'll try to keep an eye here more often.
If something is unclear don't hesitate to ask either here or on IM.

2022-12-06 18:41 UTC, giladwo commented on lib/views/pc/status/status_screen.dart
> +                                    : Colors.red,
A nicer approach would be to have a `Color Function(V, StatusItem<T, V>)` here.
It's both more useful and less error prone (i.e. one can easily confuse between `bool` cases).

2022-12-06 18:41 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +                                                  );
![image](https://user-images.githubusercontent.com/25708271/205992794-1e417afb-7b2e-4c25-afa9-05112db0ba7d.png)

This pyramid of doom... is rather inelegant.
You're trying to determine the color and name of a team.
Why not let the `Match` itself handle the messy details?
It goes along the same general approach I'm talking about below (see comment1, comment2).

2022-12-19 15:57 UTC, ItayNaumann commented on lib/views/pc/status/status_screen.dart
> +              ].contains(match.team.team);
Do you mean to add something to the DB like isRed?
if you do we don't really want to add new things to the DB because we are about the get ready for the season and don't want things to crush on us last minute...

2022-12-19 16:10 UTC, ItayNaumann commented on lib/views/mobile/team_selection_matches.dart
> +                                                  );
To which match are you referring? 
if it's match we have to add the teams number in the alliance to the DB for it to "resolve itself".
in schedule match we have that, it's either this or a lot of or's and that's messier.

2022-12-19 20:44 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +                                                  );
I'm talking about https://github.com/Team1690/Scouting-Frontend/blob/9303aaf1d6f233ececd3b0c799eb3aa76131cca7/lib/models/matches_model.dart#L3-L30

If `ScheduleMatch` had a method like `Station getTeamStation(LightTeam)` where `Station` has both an alliance color and the driver station's index this function would become much simpler.

Inside `getTeamStation`, assuming the teams are held in two private fixed-length lists, it boils down to [`firstWhere`](https://api.dart.dev/stable/2.18.6/dart-core/Iterable/firstWhere.html).

@ItayNaumann @itamarsch @amitcha06 Please join this conversation.

Do you all get where I'm going with this?

2022-12-30 17:08 UTC, giladwo requested changes
I strongly suggest you change `ScheduleMatch` so that each alliance is a (constant) list.
As you can see, this reduces [pyramids of doom](https://en.wikipedia.org/wiki/Pyramid_of_doom_(programming)) to [common](https://api.dart.dev/stable/2.18.6/dart-core/List/indexOf.html) [collection](https://api.dart.dev/stable/2.18.6/dart-core/Iterable/firstWhere.html) [methods](https://invidious.snopyta.org/watch?v=dQw4w9WgXcQ).

2023-01-03 10:26 UTC, giladwo requested changes
There's no point in having alliances if they are not used - we want the lists specifically because they make alliance-level operations (such as indexing and determining the color) easier.

2023-01-03 10:26 UTC, giladwo commented on lib/models/matches_model.dart
> +  final String Function(LightTeam) getTeamStation;
There's no need to have `getTeamStation` as a parameter, as evidenced by the fact that it is only initialized with a single implementation.

This should be a normal method that utilizes `{red,blue}Alliance`.
Here's a minimal example (the entire simplified class is here for context, the point is `Alliances#getTeamStation`):
```dart
class Alliances {
  const Alliances({required this.red, required this.blue});
  final List<int> red;
  final List<int> blue;
  
  String getTeamStation(final int n) {
    final indexOf = (final List<int> alliance) => {
      final index = alliance.indexOf(n);
      return -1 == index ? null : index;
    };
    return (indexOf(red).mapNullable((final int i) => "red${i}")
      ?? indexOf(blue).mapNullable((final int i) => "blue${i}"))!;
  }
}
```

2023-01-03 10:26 UTC, giladwo commented on lib/net/fetch_matches.dart
> +            },
Redundant, see above comment

2023-01-03 10:26 UTC, giladwo commented on lib/net/fetch_matches.dart
> +            ],
I'd create a helper like the following to simplify the alliance deserialization:
```dart
Alliance fromJson(final dynamic json, final String color) {
  final String optional = "${color}3";
  return [
    ...[0, 1, 2].map((final int index) => LightTeam.fromJson(json["${color}${i}"]))
    if optional in json:
      LightTeam.fromJson(json[optional])
  ];
}
```
(I probably have a syntax error here because I'm not using Dart regularly and don't have time to look it up, but surely @itamarsch can help get this right).

2023-01-03 10:26 UTC, giladwo commented on lib/views/pc/status/status_screen.dart
> +                        "${e.values.where((final Match element) => element.team.allianceColor == Colors.red).map((final Match e) => e.team.points).fold<int>(0, (final int previousValue, final int ele
This should become `element.redAlliance`...

2023-01-03 10:26 UTC, giladwo commented on lib/views/pc/status/status_screen.dart
> +                        "${e.values.where((final Match element) => element.team.allianceColor == Colors.blue).map((final Match e) => e.team.points).fold<int>(0, (final int previousValue, final int el
This should become `element.blueAlliance`...

2023-01-03 10:26 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
> +                            : -1,
You're supposed to be using `{red,blue}Alliance`, which obviate all this.

2023-01-03 10:26 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
> +                : Colors.blue,
Likewise, there's already a `team.color`. This is redundant.

2023-01-03 10:26 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
> +                team: StatusLightTeam(0, Colors.white, e, -1),
This is not a valid team, but this seems to require a dedicated discussion.
I'm leaving this comment here as a reminder to schedule one.

2023-01-04 21:14 UTC, ItayNaumann commented on lib/views/pc/status/status_screen.dart
> +                        "${e.values.where((final Match element) => element.team.allianceColor == Colors.blue).map((final Match e) => e.team.points).fold<int>(0, (final int previousValue, final int el
these are 2 different types of matches, 
I added the blue and red alliance to Schedule match but here we are getting a normal match, the one we get from the scouting. should I add to match a red alliance and a blue alliance?

2023-01-04 22:31 UTC, ItayNaumann commented
With all the things you asked me to make, I couldn't do them, there isn't that much time until the kickoff and I saw right there that I'm just not experienced enough for what turned out for me to be a pretty big project to start with. IDK what you want to do, close the project, just take the things that I was able to make during it, or let me work during the first couple of days of the season but I won't be able to finish until kickoff.

2023-01-05 22:36 UTC, ItayNaumann commented
I am pretty sure that I finished the changes, please check me @itamarsch @amitcha06 hopefully in friday

2023-01-06 05:44 UTC, itamarsch requested changes
You should always check the code you write after big changes like this because alot things here just won't work

2023-01-06 05:44 UTC, itamarsch commented on lib/net/fetch_matches.dart
> +  final String optional = "${color}3";
`"${color}_3"`

2023-01-06 05:44 UTC, itamarsch commented on lib/views/common/teams_search_box.dart
>            )],
We talked about this yesterday

2023-01-06 05:44 UTC, itamarsch commented on lib/views/pc/matches/change_match.dart
>      );
There might not be a third index that's why it was nullable

2023-01-06 05:44 UTC, itamarsch commented on lib/views/pc/matches/matches_vars.dart
> +          blue3: match.blueAlliance[3],
There might not be a third inded

2023-01-06 05:44 UTC, itamarsch commented on lib/views/pc/matches/matches_vars.dart
> +          red3: match.redAlliance[3],
There might not be a third index

2023-01-06 05:49 UTC, itamarsch requested changes

2023-01-06 05:49 UTC, itamarsch commented on lib/models/matches_model.dart
> +        (indexOf(false).mapNullable((final int i) => "blue ${i + 1}"))!;
What insures that the team that the function is called on is inside the ScheduleMatch?

2023-01-06 12:56 UTC, ItayNaumann commented
could someone please check once again the code @itamarsch @amitcha06 @giladwo ?

2023-01-06 15:40 UTC, itamarsch requested changes

2023-01-06 15:40 UTC, itamarsch commented on lib/net/fetch_matches.dart
> +  final String optional = "$color 3";
This still won't work you need an underscore

2023-01-06 15:40 UTC, itamarsch commented on lib/views/pc/matches/change_match.dart
> +          .mapNullable((final int p0) => p0.toString()),
number isn't nullable in this scenario so mapNullable won't do anything you need to check the length of the alliance like you did in matches_vars.dart

2023-01-06 16:15 UTC, ItayNaumann commented
[https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fsearch%2Fit-is-done-gifs&psig=AOvVaw1RRol23Jj7WN6nfsYVbnmH&ust=1673108027674000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCLinwp-rs_wCFQAAAAAdAAAAABAF](url) are we finished with this pr?

2023-01-06 16:16 UTC, ItayNaumann commented
![finished-elijah-wood](https://user-images.githubusercontent.com/93080393/211052548-b3b22872-53cd-4dc7-a8e6-c7e3e7dfd98c.gif)
is it done ? can we merge and close this pr @itamarsch @giladwo @amitcha06?

2023-01-06 16:19 UTC, itamarsch approved these changes

2023-01-06 16:19 UTC, itamarsch commented
> ![finished-elijah-wood](https://user-images.githubusercontent.com/93080393/211052548-b3b22872-53cd-4dc7-a8e6-c7e3e7dfd98c.gif)
> 
> is it done ? can we merge and close this pr @itamarsch @giladwo @amitcha06?

Yes.

2023-01-06 18:00 UTC, giladwo reviewed
I'm going to neither approve nor request changes, because we're too close to the kick-off.

Hence, this PR should be merged without more delays and all the issues raised in this review should be handled independently as technical debt.

2023-01-06 18:00 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +      },
[Failure should be loud and early](https://en.wikipedia.org/wiki/Fail-fast), even if it's temporary until we get around to avoid this nullability altogether.
Additionally, this variable is redundant.

Therefore, I'd go with
```dart
buildSuggestion: (final LightTeam team) => this.match!.getTeamStation(team)!;
```

2023-01-06 18:00 UTC, giladwo commented on lib/models/matches_model.dart
> +      return (index == -1 ? null : "$color ${index + 1}");
These parentheses are redundant.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/matches/change_match.dart
> +          : null,
\<rant>
We don't have an elegant way around this, which is rather disappointing, because Dart's stdlib could've easily been more useful were it not designed around exceptions.

This would be `blueAlliance[3].mapNullable((final LightTeam team) => team.number.toString())`.
\</rant>

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/matches/matches_screen.dart
> +                              ...<LightTeam>[...e.blueAlliance]
This is redundant, just use `e.blueAlliance.map(...)`

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/matches/matches_screen.dart
>                                    .whereType<LightTeam>()
Ditto for red alliance.
Hint: a helper that is parametrized over the alliance would eliminate this duplication.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
> +            LightTeam.fromJson(e),
`e` is parsed into a `LightTeam` way too many times here.
Do it once at the beginning and use the result.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
> +                ? scheduleMatch.redAlliance.indexOf(
You're checking both the index of and if it is contained.
This is redundant, because the index already tells you whether the team is an element of the alliance or not.

We've already got a function (which was recently discussed) that tells you the alliance and position of a given team in a given match.
Refactoring this to use it would be much more elegant.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
>              .single;
These, along with the `where` before them, should be replaced with a single `firstWhere`.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
>          return teams
This variable is redundant, just use the literal immediately

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
>                    .map((final Match e) => e.team.team)
I take it this works, but you gotta admit `match.team.team` doesn't make much sense.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
>                (final LightTeam element) => !currentValues
`currentValues` is very unindicative, I'd go with something like `nextMatches`.

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/status_screen.dart
> +                        "${e.values.where((final Match element) => element.team.allianceColor == Colors.blue).map((final Match e) => e.team.points).fold<int>(0, (final int previousValue, final int el
Yes, but it's included in another comment

2023-01-06 18:00 UTC, giladwo commented on lib/views/pc/status/fetch_status.dart
> +                  match.redAlliance.contains(e) ? Colors.red : Colors.blue,
So here's the situation:
We've got:
https://github.com/Team1690/Scouting-Frontend/blob/81d92e214bf88a930eaaf2b0de584599e75bce21/scripts/fetch_matches_tba.dart#L204-L210
https://github.com/Team1690/Scouting-Frontend/blob/931b1c291e71fe44cc6b48884d8bd4cadc8437ad/lib/views/pc/status/status_screen.dart#L333-L344

And we forgot to change where it actually matters:
https://github.com/Team1690/Scouting-Frontend/blob/931b1c291e71fe44cc6b48884d8bd4cadc8437ad/lib/models/matches_model.dart#L3-L30

We want:
- [ ] Introduce an `Alliance` to handle color and driver station position responsibilities of its teams ([`getAllianceStation`](https://github.com/Team1690/Scouting-Frontend/pull/315/files#diff-7106cb53bf25840958ffd0744e47b3fea427738dc3069cabd87ddbe3f40d73a6R19) should be a method, for instance)
- [ ] Change *all* match-related classes to use the common alliance abstraction.

This also relates to
- https://github.com/Team1690/Scouting-Frontend/pull/315/files#r1060447326

2023-01-06 18:13 UTC, giladwo submitted a review, later dismissed

2023-01-06 18:47 UTC, ItayNaumann commented
i accidentally added the change from the technical debt.....

2023-01-06 18:49 UTC, giladwo approved these changes

2023-01-06 18:50 UTC, giladwo commented
closes #318

2023-01-06 18:51 UTC, merged

2023-01-09 07:43 UTC, amitcha06 commented on lib/views/mobile/team_selection_matches.dart
> +                  IdProvider.of(context).matchType.nameToId["Practice"]!
shouldn't pre-scouting be an issue here as well?
(pre-scouting match type should show all teams)

2023-01-09 08:28 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +                  IdProvider.of(context).matchType.nameToId["Practice"]!
@scouting

2023-01-10 18:38 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +                  IdProvider.of(context).matchType.nameToId["Practice"]!
@Team1690/scouting