Fixing team selection
Team1690/Scouting-Frontend pull request #336
Opened 2023-01-09 17:43 UTC by amitcha06

fixed some bugs that were (accidentally?) commited in #315  and added pre scouting support

2023-01-09 20:24 UTC, giladwo requested changes

2023-01-09 20:24 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +          : match!.getTeamStation(p0)!,
Moving this into the above scope handles `match` being `null`, so now we need to decide what's supposed to happen if the team's station is null (which means the team is not in the match).
I reckon a helpful, indicative error message is more useful than a cryptic NPE.
How about something like
```dart
Text("the selected team ($team) is not in the selected match (${match.number}: ${match.red} vs ${match.blue})")`
```

2023-01-09 20:24 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +      buildSuggestion: (final LightTeam p0) => isNotOfficial
@itamarsch Please find a linter that prevents such poor naming.

(Yes, I know this is generated by default. It takes ~2 seconds to give parameters ok-or-better names and it's a *very* important skill. So just do it™).

2023-01-09 20:24 UTC, giladwo commented on lib/models/matches_model.dart
> +          : "${team.number} ${team.name} - $color ${index + 1}";
This fix is ready to be merged (as far as I'm concerned).
However, it is bundled in the same PR as other changes, which are not ready (see the other comments).
I'm highlighting this because this is a textbook example of how small, specific, independent PRs move faster than bigger ones, especially ones that are unfortunate enough to couple unrelated changes.

Luckily, this is in a separate commit, so it can be extracted easily.
The following should work, but you should NOT follow instructions blindly.
If anything's unclear: (0) ask about it and (1) take time to learn git [exercises](https://gitexercises.fracz.com/) and [visualisation](https://learngitbranching.js.org).
```bash
git fetch --all -p
git switch origin/master -c bugfix/add-team-number-and-name-to-team-station
git cherry-pick fixing_team_selection~
git push -u origin bugfix/add-team-number-and-name-to-team-station
# open a dedicated PR
git switch origin/master -c bugfix/handle-practice-matches-in-TeamSelectionMatches
git cherry-pick fixing_team_selection
git push -u origin bugfix/handle-practice-matches-in-TeamSelectionMatches
# open another PR and work there on the other changes
```

2023-01-10 15:08 UTC, amitcha06 commented on lib/views/mobile/team_selection_matches.dart
> +        match!.matchTypeId ==
That 2nd step would force us to check for nullability (the 2nd snippet) every time we use this widget (since match would no longer be nullable) , instead of once in the widget itself. is this really the desired option?
i have finished both anyway, so just let me know :D

2023-01-10 15:19 UTC, amitcha06 commented on lib/views/mobile/team_selection_matches.dart
> +          : match!.getTeamStation(p0)!,
What exactly do you mean by this? when a match is null we already return a Text widget instead of the TeamSelectionMatches, and when match is unofficial - practice or pre scouting (meaning the selected team wont be in the match stations), it provides all matches so the desired team can be selected (as required in these match types). so when would such issue occur? when the match is changed after the team is selected?

2023-01-10 15:24 UTC, amitcha06 commented on lib/views/mobile/team_selection_matches.dart
> +          : match!.getTeamStation(p0)!,
after testing it appears that when the match is changed after the team is selected, the team resets (so a team that is not in the selected match could not be submitted using this method, if that is what you meant)

2023-01-10 18:32 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +        match!.matchTypeId ==
@amitcha06 The idea here is to remove this nullability entirely - there's no point in allowing no state at all (the state being a match in this case).

2023-01-10 18:36 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +          : match!.getTeamStation(p0)!,
I'm making an observation here strictly using the type system: if `getTeamStation` returns `null`, `p0` does not belong to either of the alliances, and a general NPE is thrown.

However unlikely, this is allowed by the type system, and may occur sometime in the future, perhaps because of some bug. In any case, if this happens - an indicative error should be presented instead of an NPE crashing the app.

2023-01-16 18:49 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +            IdProvider.of(context).matchType.nameToId["Pre scouting"]!;
#354

2023-01-16 18:50 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +        match!.matchTypeId ==
#354

2023-01-16 18:50 UTC, giladwo commented on lib/views/mobile/team_selection_matches.dart
> +          : match!.getTeamStation(p0)!,
#354

2023-02-11 22:23 UTC, ItayNaumann commented
this came out as a really long pr, probably most of the commits here dont belong here, should i open a new pr for this?

2023-02-11 23:00 UTC, closed without merging