Updating input view
Team1690/Scouting-Frontend pull request #348
Opened 2023-01-15 19:10 UTC by amitcha06

i know this isnt a "small PR" (as we discussed, the commits were done too late), will do better next time :)
i would like this PR to be merged soon so i can keep working on it (mainly UI fixes)

2023-01-15 19:13 UTC, amitcha06 commented on lib/views/mobile/screens/input_view.dart
> +                      ],
I am aware of this code duplication, i shall open an issue about it and fix it later on as we have more pressing matters to deal with, but it will be done :)

2023-01-15 19:14 UTC, amitcha06 commented on lib/views/mobile/screens/input_view.dart
> +                      ],
again, inefficient code dupe, as stated above, will do (after this pr is merged)

2023-01-15 20:10 UTC, itamarsch requested changes

2023-01-15 20:10 UTC, itamarsch commented on lib/views/mobile/screens/input_view.dart
> +                            ],
Use darts expand function on this list

2023-01-15 20:50 UTC, ItayNaumann approved these changes
UI changes, seems good

2023-01-16 06:38 UTC, OmerPrag approved these changes

2023-01-16 06:48 UTC, itamarsch approved these changes

2023-01-16 06:59 UTC, merged

2023-01-16 08:02 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                                label: "      Failed      ",
Use `String#pad{Left,Right}` instead of hardcoding spaces.

Also, if the goal is to center the label, why only Failed? And it makes more sense to be done inside `Counter`, and by using the right `Widget` attribute.

2023-01-16 08:03 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                                onChange: (final int p0) {
Let's *not* keep `p0` (not just here, everywhere).

2023-01-16 08:06 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                            IdProvider.of(context).balance.idToName[p0]!,
Same argument as #321 applies here - there's no need to evaluate `IdProvider.of(context).balance.idToName` twice.

2023-01-16 08:09 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                              ),
Let's do better than this on Wednesday (#349) :slightly_smiling_face:

2023-01-16 18:48 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                                label: "      Failed      ",
#354

2023-01-16 18:49 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                            IdProvider.of(context).balance.idToName[p0]!,
#354

2023-01-16 18:49 UTC, giladwo commented on lib/views/mobile/screens/input_view.dart
> +                              ),
#354

2023-01-16 19:17 UTC, amitcha06 commented on lib/views/mobile/screens/input_view.dart
> +                                label: "      Failed      ",
will do.
this was a feature since early 2022 (by @itamarsch i assume), so i dont know the exact motive for this but im assuming it is only here beacuse this label was much shorter then the rest, which caused asymmetric/uncentered icons/text (compared to the other counters)

2023-01-17 15:37 UTC, amitcha06 commented on lib/views/mobile/screens/input_view.dart
> +                                label: "      Failed      ",
i will resolve this in input_view_improvements for there are more hardcoded spaces there

2023-01-17 16:17 UTC, amitcha06 commented on lib/views/mobile/screens/input_view.dart
> +                                onChange: (final int p0) {
resolved in #356 in order to avoid merge conflicts