Updating pit
Team1690/Scouting-Frontend pull request #353
Opened 2023-01-16 17:42 UTC by amitcha06

2023-01-17 16:48 UTC, itamarsch requested changes

2023-01-17 16:48 UTC, itamarsch commented on lib/views/mobile/pit_vars.dart
>    int weight = 0;
We talked about this but I think I didn't explain myself well
These values should be nullable because if the text box is empty them the use will send data that they didn't want to send and the variables should be null if the string is empty

2023-01-17 16:48 UTC, itamarsch commented on lib/views/mobile/pit_vars.dart
> +    length = 0;
`= null`

2023-01-17 16:48 UTC, itamarsch commented on lib/views/mobile/screens/pit_view.dart
>        weightContoller.text = vars.weight.toString();
`.text = ""`

2023-01-17 16:48 UTC, itamarsch commented on lib/views/mobile/screens/pit_view.dart
> +                            vars.width = value.isEmpty ? 0 : int.parse(value);
`vars.width = int.tryParse(value)`

2023-01-17 18:13 UTC, giladwo commented on lib/views/mobile/screens/pit_view.dart
> +                            vars.width = value.isEmpty ? 0 : int.parse(value);
Parsing shouldn't happen here at all - see https://github.com/Team1690/Scouting-Frontend/pull/353#discussion_r1072607213

2023-01-18 15:50 UTC, amitcha06 commented on lib/views/mobile/screens/pit_view.dart
> +                            vars.width = value.isEmpty ? 0 : int.parse(value);
> Parsing shouldn't happen here at all - see [#353 (comment)](https://github.com/Team1690/Scouting-Frontend/pull/353#discussion_r1072607213)

this widget is already digits-only keyboard. but the value is String (its a text widget), therefore the casting (it should be a number String like "9", "10"...)

2023-01-18 15:57 UTC, amitcha06 commented on lib/views/mobile/pit_vars.dart
>    int weight = 0;
got it 👍

2023-01-24 15:44 UTC, amitcha06 commented
i will open a new issue for the state managment in this screen

2023-01-24 15:50 UTC, itamarsch requested changes

2023-01-24 15:50 UTC, itamarsch commented on lib/views/mobile/pit_vars.dart
> +  int? width;
@giladwo gave a better option of instead of making these values nullable keeping them as Strings and then parsing them when sending the request so.imsted of these being `int?` they should be `String`

2023-01-24 15:50 UTC, itamarsch commented on lib/views/mobile/screens/pit_view.dart
>                    TextField(
After changing the state to a string make this widget a `TextFormField`
https://api.flutter.dev/flutter/material/TextFormField-class.html

2023-01-24 15:50 UTC, itamarsch commented on lib/views/mobile/screens/pit_view.dart
> +                        child: TextField(
https://api.flutter.dev/flutter/material/TextFormField-class.html

2023-01-24 15:50 UTC, itamarsch commented on lib/views/mobile/screens/pit_view.dart
> +                        child: TextField(
https://api.flutter.dev/flutter/material/TextFormField-class.html

2023-01-24 16:12 UTC, amitcha06 commented on lib/views/mobile/pit_vars.dart
>    int weight = 0;
so when exactly do you suggest the parsing should be? on submission?

2023-01-24 18:13 UTC, amitcha06 commented on lib/views/mobile/pit_vars.dart
> +  int? width;
are we sure this shouldnt be `String?` ? we dont want the users to submit an empty width/length (you have to set an initial value "" if its not nullable

2023-01-24 18:14 UTC, amitcha06 commented on lib/views/mobile/screens/pit_view.dart
> +                        child: TextField(
this is supposed to be a text (non input), that way the UI is [length] x [width]

2023-01-24 18:23 UTC, amitcha06 commented on lib/views/mobile/pit_vars.dart
> +  int? width;
i have done everything so far except for this, so after this answer this PR should be closed hopefully

2023-01-24 19:33 UTC, itamarsch commented on lib/views/mobile/pit_vars.dart
> +  int? width;
> are we sure this shouldnt be `String?` ? we dont want the users to submit an empty width/length (you have to set an initial value "" if its not nullable

No because when the string is nullable you have to meanings for the text field to be empty if the string isn't nullable then when the text field is empty it has to be ""

2023-01-25 00:11 UTC, giladwo commented
Reopen when ready for review

2023-01-25 17:52 UTC, amitcha06 commented
the failed check was solved in the updated version of master and will be fixed when merge

2023-01-26 17:25 UTC, amitcha06 commented
rebased changes from master so the checks now pass, thats the reason for the +35 commits O.o

2023-01-26 18:06 UTC, itamarsch requested changes

2023-01-26 18:06 UTC, itamarsch commented on lib/views/mobile/screens/pit_view.dart
> +                              : null,
Instead of checking if the width is empty run `int.tryParse` this alse checks if the string is empty and represents what we're validating better

2023-01-26 18:06 UTC, itamarsch commented on lib/views/mobile/pit_vars.dart
>        "weight": weight
This should be `int.parse(width)`

2023-01-29 17:01 UTC, giladwo commented on lib/views/mobile/screens/pit_view.dart
> +                                  : null,
This exact validator is used 4 times. I'd extract it to a helper:
```dart
String? Function(final String?) _numeric(final String error) => (final String? content) => int.tryParse(content ?? "").onNull(error);
```
and then all these are simplified to
```dart
validator: _numeric("please enter the robot's width"),
```
etc.

2023-01-29 18:12 UTC, amitcha06 commented on lib/views/mobile/screens/pit_view.dart
> +                                  : null,
i gotta look out for these, i always seem to miss them haha

2023-01-29 19:05 UTC, amitcha06 commented
there is currently a validation issue with the suggested method, on it

2023-01-31 16:46 UTC, itamarsch approved these changes

2023-01-31 16:57 UTC, merged