Fixing Id helpers
Team1690/Scouting-Frontend pull request #359
Opened 2023-01-18 15:49 UTC by ItayNaumann

2023-01-20 15:33 UTC, itamarsch requested changes
Over all looks good I saw this code when you worked on it

2023-01-20 15:33 UTC, itamarsch commented on lib/models/id_helpers.dart
> +  print(query);
😨

2023-01-20 15:40 UTC, giladwo commented on lib/models/id_helpers.dart
> +  print(query);
That's part of the reason it's a draft (which means it's not ready for review yet)

2023-01-23 16:03 UTC, giladwo commented on lib/models/id_helpers.dart
> +      );
This one uses no local closure, so it does not need to be local.

2023-01-23 16:04 UTC, giladwo commented on lib/models/id_helpers.dart
> +    """$table(order_by: {order: asc}) $tableFragment""";
The order of the result is irrelevant, so why do we need `queryOrderedEnumTable`?

2023-01-23 16:52 UTC, ItayNaumann commented on lib/models/id_helpers.dart
> +    """$table(order_by: {order: asc}) $tableFragment""";
in `lib/views/pc/matches/change_match.dart` in line 104 we use the fact that it is ordered in the selector to order them in the UI 
BTW dart maps are ordered

2023-01-23 18:18 UTC, giladwo commented on lib/models/id_helpers.dart
> +    """$table(order_by: {order: asc}) $tableFragment""";
- [ ] Better document this on the function.

This kind of implicit coupling *very* easily leads to subtle bugs.
I'd argue we can always order by `order`, but this requires all enums to have a possibly redundant column, so should just leave it at that for now.

2023-01-24 16:00 UTC, ItayNaumann commented on lib/models/id_helpers.dart
> +    """$table(order_by: {order: asc}) $tableFragment""";
in the code, you need to add better comments extension to see the highlight

2023-01-24 18:17 UTC, ItayNaumann commented
I think it's fixed but please check me @itamarsch or @giladwo

2023-01-24 19:29 UTC, itamarsch approved these changes
👍

2023-01-24 19:31 UTC, merged

2023-01-24 23:42 UTC, giladwo commented on lib/models/id_helpers.dart
> +* IdProvider.of(context).matchType.idToName.keys.toList()
I meant a link to where it's depended upon, for example `mobile/screens/input_view:_UserInputState#build`.

This lets future us see that this breaks the query over there, because <the next sentence of your comment here>.

If you use [documentation comments](https://dart.dev/guides/language/language-tour#documentation-comments) it would integrate well with the tooling, i.e. show up when you mouse over it.