introduced build.sh
Team1690/Scouting-Frontend pull request #362
Opened 2023-01-18 20:27 UTC by ItayNaumann

2023-01-19 10:08 UTC, giladwo commented
@Team1690/scouting

2023-01-20 15:31 UTC, itamarsch requested changes
Looks good look at my comment

2023-01-20 15:31 UTC, itamarsch commented on scripts/deploy.sh
> +popd
There is no need for deploy.sh anymore because we use firebase hosting this file was used when I still used github pages
I don't think we should kelp this file at all but that is pretty controversial so @giladwo @ItayNaumann @amitcha06 what are your opinions?

2023-01-20 15:38 UTC, giladwo commented on scripts/deploy.sh
> +popd
I don't see any reason to keep it if it's not used by anyone.
(The only reason to keep it is to have an easy way to use it if need be, but we have version control for this).
Just open a PR that removes this script so that if everyone confirms the PR is merged and the script is deleted.

2023-01-23 16:00 UTC, giladwo commented on scripts/deploy.sh
> +popd
The idea was to create another PR but you can just change this one's title to indicate that it actually replaces `deploy.sh` with `build.sh` and deletes `deploy.ps1`

2023-01-23 16:29 UTC, itamarsch approved these changes

2023-01-23 16:29 UTC, merged