Introducing enums
Team1690/Scouting-Frontend pull request #367
Opened 2023-01-30 16:46 UTC by ItayNaumann

2023-01-31 15:54 UTC, itamarsch requested changes

2023-01-31 15:54 UTC, itamarsch commented on lib/views/mobile/screens/fault_view/change_fault_status.dart
> +              ).faultStatus.enumToId["No progress"],
Check all enumToId call that you are passing an enum.and not a string because this won't work

2023-01-31 16:14 UTC, ItayNaumann commented on lib/views/mobile/screens/fault_view/change_fault_status.dart
> +              ).faultStatus.enumToId["No progress"],
There are a couple of names of lists we were using their name and displaying in the app ( these enums: MatchType, DriveMotor, Balance, DriveTrain), what should I do with them?

2023-02-05 12:12 UTC, ItayNaumann commented
i think i closed this pr so that #356 wont have that much merge conflicts and they will be here instead just to close it faster

2023-02-05 15:28 UTC, giladwo commented
> i think i closed this pr so that #356 wont have that much merge conflicts and they will be here instead just to close it faster

How does this relate to #356 exactly?

Anyways, haven't we agreed we'd rather have closed modules that model the domain (i.e. a `balance.dart` module with its underlying enum, `IdProvider`, widget for input, widget for display and whatever else we need about `balance` in Charged Up)?

2023-02-06 15:11 UTC, closed without merging