tried to change the onChange in team search box
Team1690/Scouting-Frontend pull request #377
Opened 2023-02-02 14:45 UTC by ItayNaumann

2023-02-03 00:05 UTC, ItayNaumann commented
got a bit long there, will add the firebase changes in another commit.

2023-02-03 08:05 UTC, itamarsch commented
This PR looks Huge but it's mostly ui changes so git says it's a alot

2023-02-03 08:21 UTC, itamarsch requested changes

2023-02-03 08:21 UTC, itamarsch commented on lib/views/mobile/firebase_submit_button.dart
> +            Map<String, dynamic>.from(widget.toHasuraVars());
You don't need this call to `from`

2023-02-03 08:21 UTC, itamarsch commented on lib/views/pc/team_info/team_info_screen.dart
> +          ),
Make this a function and have the function receive a body (in this case a `TeamInfo` or `NoTeamSelected`) and a searchBox
and then pass a call to the function with the correct parameters for buildWithTeam and buildWithoutTeam

2023-02-03 15:37 UTC, giladwo commented
![image](https://user-images.githubusercontent.com/25708271/216642581-7fe83ece-bde6-4fab-891b-b632116d8131.png)
![image](https://user-images.githubusercontent.com/25708271/216643161-0704a038-cba1-4e4f-877f-50da0a4c93c0.png)

There are way too many changes here, and they probably don't belong on the same PR.
Unless you can convince me they do, please split them into smaller PRs (shouldn't take long, provided the changes were 
carefully committed separately).

2023-02-03 15:37 UTC, closed without merging

2023-02-03 15:41 UTC, giladwo commented
We don't want a mega PR that handles all open issues. We want small PRs, even multiple ones per issue (when it makes sense, i.e. a methodological change that should be applied to different parts).

2023-02-05 08:23 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216808562-a327317d-c9a9-4132-8bdf-202049e72a18.png)
![image](https://user-images.githubusercontent.com/93080393/216808771-4c6af7c6-a5ef-431b-8b74-2c83158faaaa.png)
we are removing here not needed default values to send hasura,setting them as the default for the class and removing the to hasura vars function and moving it to the only time we use it and removing the team from the class. probably not needed in this pr should be on another pr.

2023-02-05 08:24 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216808912-d5c86184-ef60-495c-a503-72b9620a50d4.png)
switched to the new way we are using teamSelectionFuture

2023-02-05 08:40 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216808944-bd207918-ab7a-4f6c-b768-5d5f92c54bab.png)
![image](https://user-images.githubusercontent.com/93080393/216808959-d2bfc84f-0bbc-4a6e-b29e-db5c27bdfc95.png)
![image](https://user-images.githubusercontent.com/93080393/216809419-6df51a72-00b9-4c77-8f5d-d9c9f4eac555.png)
this is the main change of the pr, changing teamSearchBox, in here we are getting from where its called a couple of functions.
setTeam is to be able to have a onSelected cause we are setting up the widget here so the place it is called to be cant access it without it.
on build we have 2 functions; build with team and build without team. we are calling build with team when we have team and when its null we are calling build without team.
also using the setTeam function instead of using setState directly.

2023-02-05 08:44 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216809696-46883a9b-9fa5-47c9-aba2-4ac52c74ba37.png)
in here we probably went too far for this pr; removed the HasuraVars file and changed the submit button to get a toHasuraVars function

2023-02-05 08:55 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216809863-8f96f770-ad8a-4e16-a26e-9dd36600497c.png)
removed the toHasura vars in pit vars and removed the team from pit vars

2023-02-05 09:50 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216812149-c9129248-2c39-41e5-8952-29ce39d57504.png)
in here (fault view) its just changed to the new way we use teamSelectionFuture and we removed team from it

2023-02-05 10:01 UTC, ItayNaumann commented
in input view the git diff is no better than the normal diff, but we just removed lightTeam from there, changed to the new way it shows only the match and team search boxes, but then it builds the whole screen after he gets both of these variables,also defined the parsing "toHasuraVars" in the file instead of in the vars of  this file

2023-02-05 10:10 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216812950-c6c6c47d-e96c-4a04-8248-f98a8a283776.png)
changed to new teamSelectionFuture, changed from a list of controllers to each controller by himself and moved the parse to hasura vars to here

2023-02-05 10:14 UTC, ItayNaumann commented
in specific view its pretty much the same as input view; removed the list of controllers, changed to new teamSelectionFuture version and moved the definition of the toHasuraVars to here and changed that the screen wouldnt be shown until the user inputed a match and a team

2023-02-05 10:15 UTC, ItayNaumann commented
side nav bar just changed to new team selecitonFuture
![image](https://user-images.githubusercontent.com/93080393/216813280-3a296f00-2493-4373-8e62-2375c7c4a48c.png)

2023-02-05 10:16 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216813296-63fa6947-1dea-49ab-a7a6-22374e0ceb1c.png)
in specific vars simply removed the toHasuraVars function and removed lightTeam from being defined there

2023-02-05 10:17 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216813325-50c679c2-6e6b-4668-8785-0b829dc4a884.png)
in the submit button just changed it from getting a map of string to dynamic to a function that returns that map

2023-02-05 10:19 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216813385-973c6e22-9030-46ea-9a23-611e3053be3d.png)
in teamSelectionMatches just changed to include new features from teamSelectionFuture

2023-02-05 10:25 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216813467-83700aee-c222-4977-bdf5-9a9baa78fa86.png)
in compare screen we remove all of the controllers from this scope and add before the return of the search box the teams that arent in the list full of teams

2023-02-05 10:35 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216813955-7a7856af-dd87-4efd-bc89-649b371cf2ce.png)
![image](https://user-images.githubusercontent.com/93080393/216813968-1ae196ee-e5e1-4bee-938f-0d2fa12b9b7d.png)
![image](https://user-images.githubusercontent.com/93080393/216813976-e0d999d1-b205-411a-8ca2-73e852a745c2.png)
making an empty array of void functions that reset the search box and defining each one of them to a different search box and then after we send the info to the db we reset all of them at once

2023-02-05 10:36 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216814115-6c997d6a-baf1-46cc-89a3-ee7cf62bd93f.png)
removing the sending to db here...

2023-02-05 10:38 UTC, ItayNaumann commented
![image](https://user-images.githubusercontent.com/93080393/216814163-10f7ed25-a2ee-4e78-870f-727c606ecb94.png)
changing to new way of teamSelectionFuture

2023-02-05 10:46 UTC, ItayNaumann commented
I think i can make this pr 2 pr, one for removing the hasura things and one for all the others

2023-02-05 11:56 UTC, amitcha06 commented
> ![image](https://user-images.githubusercontent.com/93080393/216809696-46883a9b-9fa5-47c9-aba2-4ac52c74ba37.png) in here we probably went too far for this pr; removed the HasuraVars file and changed the submit button to get a toHasuraVars function

Yeah These should NOT be on the same PR

2023-02-05 11:57 UTC, amitcha06 commented
> in input view the git diff is no better than the normal diff, but we just removed lightTeam from there, changed to the new way it shows only the match and team search boxes, but then it builds the whole screen after he gets both of these variables,also defined the parsing "toHasuraVars" in the file instead of in the vars of this file

Note that #356 is not merged yet, so there will be merge conflicts

2023-02-05 12:05 UTC, amitcha06 commented
> in specific view its pretty much the same as input view; removed the list of controllers, changed to new teamSelectionFuture version and moved the definition of the toHasuraVars to here and changed that the screen wouldnt be shown until the user inputed a match and a team

i would argue that anything unrelated to TeamSelection should not be in this PR (the controllers, for example)

2023-02-05 12:06 UTC, amitcha06 commented
> ![image](https://user-images.githubusercontent.com/93080393/216813296-63fa6947-1dea-49ab-a7a6-22374e0ceb1c.png) in specific vars simply removed the toHasuraVars function and removed lightTeam from being defined there

Same as stated above, the HasuraVars shouldnt be in this PR

2023-02-05 12:07 UTC, amitcha06 commented
> ![image](https://user-images.githubusercontent.com/93080393/216813325-50c679c2-6e6b-4668-8785-0b829dc4a884.png) in the submit button just changed it from getting a map of string to dynamic to a function that returns that map

^

2023-02-05 12:08 UTC, amitcha06 commented
> ![image](https://user-images.githubusercontent.com/93080393/216813955-7a7856af-dd87-4efd-bc89-649b371cf2ce.png) ![image](https://user-images.githubusercontent.com/93080393/216813968-1ae196ee-e5e1-4bee-938f-0d2fa12b9b7d.png) ![image](https://user-images.githubusercontent.com/93080393/216813976-e0d999d1-b205-411a-8ca2-73e852a745c2.png) ![image](https://user-images.githubusercontent.com/93080393/216814092-5dde3342-ea13-4cc4-abf6-ba7499a28121.png) making an empty array of void functions that reset the search box and defining each one of them to a different search box and then after we send the info to the db we reset all of them at once and defining the sending to db here..

These should also be split

2023-02-05 12:09 UTC, amitcha06 commented
> ![image](https://user-images.githubusercontent.com/93080393/216814115-6c997d6a-baf1-46cc-89a3-ee7cf62bd93f.png) removing the sending to db here...

^

2023-02-05 12:10 UTC, amitcha06 commented
> I think i can make this pr 2 pr, one for removing the hasura things and one for all the others

They can probably even more. 
one for the TeamSelection
one for HasuraVars
one for the changes in matches_screen,
etc...