Updating scatter
Team1690/Scouting-Frontend pull request #379
Opened 2023-02-02 19:17 UTC by amitcha06

2023-02-03 08:42 UTC, itamarsch requested changes

2023-02-03 08:42 UTC, itamarsch commented on lib/views/pc/scatter/fetch_scatter.dart
> +              yStddevGamepiecePoints /= matchesGamepiecePoints.length;
This can be 
```dart
final double yStddevGamepiecePoints = matchGamepiecePoint.map((match) => (match - gamepiecePointAvg).abs()).avg()

```

2023-02-03 08:42 UTC, itamarsch commented on lib/views/pc/scatter/fetch_scatter.dart
> +            .where((final ScatterData? data) => data != null)
this can be 
`.whereType<ScatterData>()`

2023-02-03 16:13 UTC, giladwo requested changes

2023-02-03 16:13 UTC, giladwo commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
Do you all @Team1690/scouting not see anything wrong here?

2023-02-05 07:44 UTC, amitcha06 commented on lib/views/pc/scatter/fetch_scatter.dart
> +              yStddevGamepiecePoints /= matchesGamepiecePoints.length;
I like this👍

2023-02-05 08:02 UTC, amitcha06 commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
Are you talking about everything being nullable here? The idea was that we cant do null addition. Are you suggesting we should remove the nullability earlier? before the function?

2023-02-05 16:16 UTC, giladwo commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
I'm waiting for @ItayNaumann and @itamarsch's take on this.

Hint: there are many conditions here, and this is behavior isn't about decision making (so there really shouldn't be any conditionals involved).

2023-02-06 08:23 UTC, amitcha06 commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
By the way, what stopps us from checking if 'data' is null, instead of it's values multiple times? 
something like (obviously not exactly like this)
![image](https://user-images.githubusercontent.com/71347633/216920772-30090e3b-effc-4449-9029-2c721af0693b.png)
and so on and so forth...

2023-02-06 08:58 UTC, amitcha06 commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
![image](https://user-images.githubusercontent.com/71347633/216928186-607791b8-3c0f-4313-806e-da8fb1f18bcd.png)
made this during a free lesson. It works. is this what you wanted? (again, not the "final product", just the idea)

2023-02-06 09:00 UTC, amitcha06 commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
this could probably be even shorter using some collection magic

2023-02-06 15:08 UTC, ItayNaumann commented on lib/views/pc/scatter/fetch_scatter.dart
> +}
I thought i commented earlier but it didn't send the comment, i said the maybe we can add a check at the start if one of them is null and then call the function (which i see you did), or do a whereType for the query (but this wont work because its sending it as dynamic) or lastly make like we done on the first time on id-helpers and made a default value and just changed some unique feature about the info we want

2023-02-12 13:09 UTC, amitcha06 commented
this PR is only waiting for #390

2023-02-15 09:16 UTC, itamarsch approved these changes

2023-02-15 10:11 UTC, ItayNaumann approved these changes

2023-02-15 10:44 UTC, ItayNaumann commented
@giladwo could you review this once again? we are waiting for your review so we can merge (you requested changes in the past so it wont let us merge without your review....)

2023-02-15 12:50 UTC, giladwo approved these changes
Blind ok

2023-02-15 13:00 UTC, merged