fixed status' bugs... (works now on the match 2022)
Team1690/Scouting-Frontend pull request #391
Opened 2023-02-12 17:04 UTC by ItayNaumann

2023-02-12 18:29 UTC, ItayNaumann commented
waiting for #390 to merge...

2023-02-14 20:02 UTC, OmerPrag submitted a review, later dismissed

2023-02-15 09:09 UTC, amitcha06 commented
Please rebase to the current master branch

2023-02-15 09:10 UTC, amitcha06 commented
Please rebase to the current master branch

2023-02-15 09:20 UTC, itamarsch requested changes

2023-02-15 09:20 UTC, itamarsch commented on lib/views/pc/status/status_screen.dart
> +  final Widget Function(V)? builder;
Why did you rename this?

2023-02-15 13:12 UTC, itamarsch submitted a review, later dismissed

2023-02-15 19:24 UTC, amitcha06 approved these changes

2023-02-15 19:30 UTC, OmerPrag approved these changes

2023-02-15 19:39 UTC, merged