Creating match and team selection
Team1690/Scouting-Frontend pull request #393
Opened 2023-02-13 12:06 UTC by ItayNaumann

2023-02-14 19:48 UTC, amitcha06 approved these changes
We went over this together, but maybe we should further think about/discuss removing MatchesSelectionFuture. We may need this in the future. Either way its not that hard to redo so not that big of deal

2023-02-14 20:26 UTC, itamarsch requested changes

2023-02-14 21:30 UTC, itamarsch approved these changes

2023-02-15 09:00 UTC, amitcha06 approved these changes
yeah this makes more sense

2023-02-15 09:02 UTC, merged