Updating picklist
Team1690/Scouting-Frontend pull request #394
Opened 2023-02-13 14:53 UTC by amitcha06

2023-02-13 22:08 UTC, ItayNaumann commented on lib/views/pc/picklist/fetch_picklist.dart
> +      matchesBalanced:
i dont think about a better name for this but from the name it sounds like only the matches where the team was balanced, not including unbalanced...

2023-02-13 22:09 UTC, ItayNaumann requested changes
we have the commits from #390 ... cherry-pick or just rebase push -f

2023-02-13 22:11 UTC, ItayNaumann commented
accidently merged into current master, could be reversible very easily, mb......

2023-02-14 08:05 UTC, ItayNaumann commented
i merged the 2 last commits into 1 and removed all the commits that master already had

2023-02-14 08:11 UTC, ItayNaumann submitted a review, later dismissed
Just did the push -f, looks good to me and there are no longer the main's commits

2023-02-14 18:31 UTC, OmerPrag approved these changes

2023-02-14 19:51 UTC, OmerPrag approved these changes

2023-02-14 19:52 UTC, Ido-Sobol approved these changes

2023-02-14 19:52 UTC, merged