Updating team info
Team1690/Scouting-Frontend pull request #402
Opened 2023-02-15 19:23 UTC by amitcha06

2023-02-15 21:45 UTC, itamarsch requested changes

2023-02-15 21:45 UTC, itamarsch commented on lib/views/pc/team_info/models/fetch_team_info.dart
> +        List<int> getBalanceLineChart(final String mode) => matches
This can be a `bool mode`

2023-02-15 21:45 UTC, itamarsch commented on lib/views/pc/team_info/models/fetch_team_info.dart
> +                4,
Why is this 4 and not 1?

2023-02-16 08:44 UTC, itamarsch submitted a review, later dismissed

2023-02-16 11:47 UTC, ItayNaumann approved these changes

2023-02-16 12:34 UTC, itamarsch approved these changes

2023-02-16 12:35 UTC, merged